### ISSUE TITLE
Run examples in the documentation as tests

### ISSUE THREAD

**Issue by dalonsoa** [EnergySystemsModellingLab/MUSE_OS#164]
The documentation includes numerous scenarios that should run successfully  as the code evolves. Run the scenarios as regression tests can be implemented as as in #161

**Comment by sgiarols** [comment]
These labels can be used to run the tests when they are needed. For example, in the case of the documentation, ideally when the test runs can also give the output to the documentation tutorials and notebooks so that things are not repeated.
