### ISSUE TITLE
MUSE overinvests in capacity in the default model [BUG] 

### ISSUE THREAD

**Issue by ahawkes** [EnergySystemsModellingLab/MUSE_OS#194]
## Describe the bug
A clear and concise description of what the bug is, including error messages.

In the "default" model, MUSE appears to be incorrectly calculating the required capacity for investment (i.e. that needed to serve demand). Peak heat demand in each milestone year is:

Year 2020, 2025, 2030, 2035, 2040, 2045, 2050
Peak   18,   23.5,   29,    34.5,   40,     45.5,  51
Boiler 10,    5,        4.1,    4.1,    0.91,   0.91,   0
HP     0,      19,       25.9,  31.9, 41.09,  47.09, 54,
Total  10,    24,      30,     36,     42,     48,     54

When you compare Total and Peak in this table, you see that Total is always a bit above Peak. Total should equal Peak in this case (I do note that there are cases where Total can exceed Peak - e.g. when demand is decreasing but asset lives extend into the future - but that is not true in this case).

## To Reproduce
Steps to reproduce the behavior. Attache any input file that might be required.

Run the default model, look at the results.

## Expected behavior

We need to look at the algorithm which decides how much capacity is required for investment. It seems to be overestimating this quantity. This might relate to questions I've raised previously about use of the dispatch algorithm during the investment step - how one must know dispatch of existing assets and potential new assets before one can decide how much capacity to invest in.

## Context

Please, complete the following to better understand the system you are using to run MUSE.

- Operative system (eg. Windows 10): Windows 10
- MUSE version (eg. 1.0.1): 1.0.2
- Installation method (eg. pipx, pip, development mode): pipx
- Python version (you can get this running `python --version`): 3.9.13

**Comment by dalonsoa** [comment]
Most likely fixed alongside #323

**Comment by dalonsoa** [comment]
@ahawkes I've been trying to reproduce this and, for what I can tell, the peak demand and the total capacity are matched. See the following table, where I calculate the peak demand out of the preset residential consumption at 2020 and 2050, which are the inputs. Consumption for intermediate years are interpolated. 

![Image](https://github.com/EnergySystemsModellingLab/MUSE_OS/assets/6095790/f3f57d1a-c3bd-43dc-a69e-95ab499efc31)

The last column, which will be the yearly consumption based on the peak heat demand matches exactly the total capacity of technologies producing heat that you indicated (except for 2020, naturally). Am I looking at the right place?

**Comment by ahawkes** [comment]
Thanks @dalonsoa - right OK - yes your calculation looks right so I'm not sure where mime came from - it was a while ago. Anyway assuming that when run, the default model invests those capcities and not more, all is well. Thanks!

**Comment by dalonsoa** [comment]
Ok, then I'm closing this as things seem to add up.
