### ISSUE TITLE
[BUG] MUSE sometimes fails when existing capacity is set to zero

### ISSUE THREAD

**Issue by ahawkes** [EnergySystemsModellingLab/MUSE_OS#204]
## Describe the bug
A clear and concise description of what the bug is, including error messages.

Existing capacity of a technology can be zero. But setting this as such sometimes causes an error (ValueError: technology must not be empty).

## To Reproduce
Steps to reproduce the behavior. Attache any input file that might be required.

This seems random - users have reported it

## Expected behavior

Existing capacity should always be allowed to be zero. Or, if there is a really good reason for this behaviour, the error must be caught and a clear description of how to fix it given to the user.

## Context

Please, complete the following to better understand the system you are using to run MUSE.

- Operative system (eg. Windows 10): Windows 10
- MUSE version (eg. 1.0.1): 1.0.2
- Installation method (eg. pipx, pip, development mode): pipx
- Python version (you can get this running `python --version`): 3.9.13

**Comment by tsmbland** [comment]
Fixed by #299
