### ISSUE TITLE
Documentation "9.3.7. Agents" has a number of poorly explained parameters

### ISSUE THREAD

**Issue by ahawkes** [EnergySystemsModellingLab/MUSE_OS#206]
## Describe the bug
A clear and concise description of what the bug is, including error messages.

Confusing descriptions reported by users for several parameters here: 

AgentShare
Name of the share of the existing capacity assigned to this agent. Only meaningful for retrofit agents. The actual share itself can be found in [Techno-data](https://muse-os.readthedocs.io/en/latest/inputs/technodata.html#inputs-technodata).

Quantity
A factor used to determine the demand share of “New” agents.

MaturityThreshold
Parameter for the search rule [maturity](https://muse-os.readthedocs.io/en/latest/api.html#muse.filters.maturity).

SpendLimit
Parameter for the search rule spend_limit.

## To Reproduce
Steps to reproduce the behavior. Attache any input file that might be required.

## Expected behavior

Changes needed:
AgentShare - explain why this is needed and how it is used with an example
Quantity - explain why this is needed and how it is used with an example
MaturityThreshold - explain why this is needed and how it is used with an example
SpendLimit - explain why this is needed and how it is used with an example

## Context

Please, complete the following to better understand the system you are using to run MUSE.

- Operative system (eg. Windows 10):
- MUSE version (eg. 1.0.1):
- Installation method (eg. pipx, pip, development mode):
- Python version (you can get this running `python --version`):

**Comment by tsmbland** [comment]
Closed by 453de903ee65090ecc3741617787eaa60cf2c619 and 5a29e077a8baded8ab2f1b392a9d69c8f9e9241e
