### ISSUE TITLE
Artificial error shown on pytest tutorial n.7

### ISSUE THREAD

**Issue by sgiarols** [EnergySystemsModellingLab/MUSE_OS#217]
For what I can say, the problem seems to have to do with how the tests are setup and nothing to do with the actual error being reported. Running:

```bash
python -m pytest .\tests\test_fullsim_regression.py
```

works totally fine. However, running:

```bash
python -m pytest -m "regression"
```

results in the errors reported.

I've isolated the tutorial regression tests with their own mark (`mark.tutorial`), so they can be run totally independently of any other regression tests with `pytest -m "tutorial"`, and things still fail in the same way. So the only conclusion I have so far is that it must be related with how the test suit is setup when marks are used compared to just running all the tests in a file (which works fine).

Considering this diagnosis, I think that, despite the failing test, this PR is safe to merge as the failure is artificial and not related with the tutorials being wrong or an error in the MUSE code itself.

_Originally posted by @dalonsoa in https://github.com/EnergySystemsModellingLab/MUSE_OS/issues/177#issuecomment-1792081869_

**Comment by sgiarols** [comment]
@dalonsoa it seems that python -m pytest .\tests\test_fullsim_regression.py uses the code of the current branch whereas python -m pytest -m "regression"uses the develop branch... Not sure that this is possible

**Comment by dalonsoa** [comment]
That's... odd. I don't know how that can be possible. Why do you think that is what is happening?
