### ISSUE TITLE
Redundant columns in consumption_path input file

### ISSUE THREAD

**Issue by martinstringer** [EnergySystemsModellingLab/MUSE_OS#220]
## Is your feature request related to a problem? Please describe.
The consumption_path input file currently requires an index column, “ProcessName”, and “TimeSlice” to be present even if they are not being used in the simulation. 

Though this is stated in the documentation, it is right down in section 9.2.6 and no error message is generated if the columns are missing. In any case, there would ideally be no requirement for redundant columns in inputs.

## Describe the solution you'd like
Full solution: Modify MUSE so that these columns are optional unless required for consistency with other input files.

Temprorary solution: Generate explanitory error message when these columns are missing.

**Comment by tsmbland** [comment]
This has been fixed. The index column and `ProcessName` are no longer required. `Timeslice` is still required, but if you don't want to specify demand on a timeslice level, you should use the `demand_path` format instead. See documentation [here](https://muse-os.readthedocs.io/en/latest/inputs/toml.html#preset-sectors) (although admittedly this could be much clearer)
