### ISSUE TITLE
Meaning of "fixed" vs "flexible" level is unclear

### ISSUE THREAD

**Issue by tsmbland** [EnergySystemsModellingLab/MUSE_OS#263]
The documentation mentions that the "Level" parameter in the technodata and commodities files can be "fixed" or "flexible", but the meaning of these two options isn't adequately explained.

Sections to look at:
9.3.3 Techno-data (`docs/inputs/technodata.rst`)
9.3.5 Commodities (`docs/inputs/commodities_io.rst`)

Update: #374 has changed the technodata files (and documentation) to no longer include the Level parameter as it wasn't being used

**Comment by tsmbland** [comment]
I've been digging into the code to try and work out what the `Level` parameter (fixed vs flexible) is doing.

For input commodities, it's used in the [`consumption` function in `quantities.py`](https://github.com/EnergySystemsModellingLab/MUSE_OS/blob/a2a1b4f3d8bf4166ee57056b569584234a454883/src/muse/quantities.py#L256), where it's chosing amongst the different flexible inputs based on the price. So, for example, a boiler would get to choose between two different types of fuel based on which one was cheapest at the time. I don't think the calculation is necessarily correct (for example, what if fuel A is cheaper per unit than fuel B, but less efficient so you have to use more of it?), but does that sound about right as the intended meaning of this parameter? @ahawkes @dalonsoa 

(As a side note, I think the calculation of fuel costs in LCOE needs to change as it's adding all the flexible inputs together when it should be selecting just one of them)

For output commodities, this parameter doesn't appear to be used at all (outputs with Level="flexible" end up being ignored in all the calculations). In this case, it's probably best to remove this column from the `CommOut` file.

**Comment by ahawkes** [comment]
Yes that sounds like the intention (and yes the investor should be choosing based on cost of outputs, which are in turn a function of cost on inputs). Also yes LCOE calculation could be off - but if this is the LCOE calculation to determine investment then it might be OK (i.e. it would be hard to justify singling out one commodity output if there are several). Note that flexible processes are mainly used for refineries (that have flexible output), and a bit in transport (e.g. flexible fuel like % ethanol), and as you've noted some heat techs.

**Comment by tsmbland** [comment]
Ok thanks. So a flexible output would mean that a technology could choose between multiple outputs (with the same inputs?), based on which output has the highest market value at the time?

(At least is that the intention? - it's not actually doing that...)

**Comment by ahawkes** [comment]
Along those lines yes - assuming there will be demand for the output commodities - the technology can adjust the amount of output of each to match demand. Also - yes - if there are other technologies that can produce these commodities it will (should!) prefer the cheaper one. Similar logic applies when the flexible commodities are on the input side - it will (should!) use the cheaper ones.
________________________________

**Comment by dalonsoa** [comment]
Nope, the LCOE used in investments is [this other one defined in `objectives.py`](https://github.com/EnergySystemsModellingLab/MUSE_OS/blob/a2a1b4f3d8bf4166ee57056b569584234a454883/src/muse/objectives.py#L547). 

Again, like with the discussion on the supply we have in #335, I have the suspicion that the LCOE linked by @tsmbland above is not really used with the `scipy` solver, but only with the `adhoc` solver, as the `scipy` solver does the investment and the dispatch in one go by solving the matrix.
