### ISSUE TITLE
Integrate error message after merging https://github.com/SGIModel/MUSE_OS/pull/20

### ISSUE THREAD

**Issue by sgiarols** [EnergySystemsModellingLab/MUSE_OS#30]
Another to refer is here
https://github.com/SGIModel/MUSE_OS/blob/c4e71cdaf19e2cbf86440a05bd07fade47c44cd7/src/muse/investments.py#L283

_Originally posted by @sgiarols in https://github.com/SGIModel/MUSE_OS/pull/13#discussion_r830188781_

**Comment by tsmbland** [comment]
I don't know what this issue refers to, so I'm going to close it
