### ISSUE TITLE
[BUG] Fix spelling "threshhold" -> "threshold"

### ISSUE THREAD

**Issue by alexdewar** [EnergySystemsModellingLab/MUSE_OS#301]
There are lots of places where the incorrect spelling "threshhold" is used. Annoyingly, some of those places are in the names of fields in config files, so if we blindly rename them we will break backwards compatibility. Accordingly, we should probably deprecated these misspelled fields and issue a warning if the user uses them and add fields for the correctly spelled variant.

**Comment by tsmbland** [comment]
@alexdewar Mind if I take this?

**Comment by alexdewar** [comment]
Nope, go ahead!

**Comment by alexdewar** [comment]
My plan was to check what happens if you specify one of the old misspelled variants of the option names after we change it, because we don't want default values to be substituted into users' models.

**Comment by tsmbland** [comment]
Good point. There are three parameters:

`asset_threshhold`: this is defined in settings.toml. If we rename this, then if someone uses the old spelling it will ignore this and use the default value. I guess we could raise an error if the incorrect spelling is found and prompt users to rename the parameter.

`maturity_threshhold`: this is the internal name for the parameter defined as MaturityThreshold (correct spelling) in the Agents.csv file - so no problems here.

`demand_threshhold`: as far as I can tell there is no way for the user to define this, and it will always use the default vaule. So no problems renaming this, but I assume something is incomplete here
