### ISSUE TITLE
Combined capacity should exactly match the maximum demand of all timeslices

### ISSUE THREAD

**Issue by dalonsoa** [EnergySystemsModellingLab/MUSE_OS#323]
No more, no less - the combined capacity should be equal to the maximum demand required in any timeslice. Two options to implement this:

- Implement an inequality constrain that enforces that the capacity must not exceed the maximum demand.
- Implement an equality constrain the strictly enforces this. 

Both will be explored in terms of ease of implementation and performance.

**Comment by alexdewar** [comment]
@dalonsoa Did you say that fixing this issue may also close #317?

**Comment by dalonsoa** [comment]
Nope, #194

**Comment by dalonsoa** [comment]
Needs #336
