### ISSUE TITLE
[BUG] Branch protection rules might need updating

### ISSUE THREAD

**Issue by alexdewar** [EnergySystemsModellingLab/MUSE_OS#326]
I don't think all the required status checks can be in the list because I just enabled auto-merge on my PR and it merged immediately.

I can't dig into this because I don't have admin rights. @dalonsoa?

**Comment by dalonsoa** [comment]
Sorted! Now you can :)

**Comment by alexdewar** [comment]
Thanks!

**Comment by alexdewar** [comment]
I've made all the Python 3.9 tests required and when we merge #298 I'll update it to include the Python 3.12 ones.

**Comment by alexdewar** [comment]
I've finished update the rules for the `develop` branch
