### ISSUE TITLE
Homogenise database schemas for MUSE1 and MUSE2

### ISSUE THREAD

**Issue by tsmbland** [EnergySystemsModellingLab/MUSE_OS#330]
Myself and Adam have put together a couple of draft database schemas for MUSE1 and MUSE2 respectively. See [here](#285) and [here](https://github.com/EnergySystemsModellingLab/MUSE_2.0/discussions/51). Ideally we want the two databases to be as similar as possible, to simplify development and ease the transition for users. Some differences will be unavoidable, but these should be flagged. I will aim to bring my MUSE1 schema in line with Adam's MUSE2 schema, but some changes may be necessary to the MUSE2 schema (e.g. creating tables for the one-to-many relationships).

**Comment by tsmbland** [comment]
I've had a go at putting together a database schema for MUSE1 that follows the same structure as schema we have for MUSE2. See https://lucid.app/lucidchart/0fa3cd6c-aa69-4397-b432-024be7acb22e/edit?viewport_loc=146%2C-101%2C4476%2C1707%2C0_0&invitationId=inv_c2989e36-7e9d-4865-abf5-d258fd73b274

Fields specific to MUSE1 are in green, and fields specific to MUSE2 are in red. I still have quite a few questions (mostly for Adam) which are included as comments in the document.

I've also had a go at putting together corresponding a set of csv files for the default model that comes with MUSE1:
[muse1_default_new_inputs.zip](https://github.com/user-attachments/files/15821568/muse1_default_new_inputs.zip)

@ahawkes @dalonsoa @alexdewar Have a look and let me know what you think

**Comment by dalonsoa** [comment]
I've had a look at the schemas and left a couple of comments. To be honest, they are very different - a lot of green and red stuff - but hopefully this exercises will help to figuring out what is really needed in MUSE2 and what we don not want from MUSE1.

**Comment by alexdewar** [comment]
Looks good! Honestly I'm not sure I have much to add beyond what @dalonsoa has said already. I guess we can work out any problems as we go along.
