### ISSUE TITLE
Change `MinimumServiceFactor` for `default_timeslices` model

### ISSUE THREAD

**Issue by tsmbland** [EnergySystemsModellingLab/MUSE_OS#334]
Currently the `MinimumServiceFactor` for the `default_timeslices` model is set to 1 for all timeslices. This essentially constrains supply to 100% in every timeslice, which isn't a realistic scenario. We should change this to zero.

**Comment by HarmonicReflux** [comment]
Observation:

User guide MUSE_OS/docs/user-guide/min-max-timeslice-constraints.ipynb,
states that, upon invoking 
`python -m muse --model default_timeslice --copy PATH/TO/COPY/THE/MODEL/TO`
, in my case, 
`python -m muse --model default_timeslice --copy /home/bjs/Downloads/vcs/MUSE_OS/ResultsDefaultTimeSlice`,

there should be additional `TechnodataTimeslices.csv` file in the `power` and `residential` sectors. These files should both contain a column `MinimumServiceFactor`.

The file "TechnodataTimeslices.csv", located in 
MUSE_OS/ResultsDefaultTimeSlice/model/technodata/power/
does contain the column `MinimumServiceFactor`. However, 
the file "TechnodataTimeslices.csv" located under
MUSE_OS/ResultsDefaultTimeSlice/model/technodata/residential/TechnodataTimeslices.csv
does not (see attached screenshots).

![residential_TechnodataFimeslices](https://github.com/EnergySystemsModellingLab/MUSE_OS/assets/16504600/32fe1c7b-2a73-4920-8025-5bbe77348a5e)
![power_TechnodataTimeslices](https://github.com/EnergySystemsModellingLab/MUSE_OS/assets/16504600/75cfbe86-2997-49c0-838b-2d2e1c339030)

**Comment by tsmbland** [comment]
Well spotted! You're correct that the residential sector file should have a `MinimumServiceFactor` column. Just to confuse things even more, it seems that this file isn't actually used at all, as it's not referenced in the `settings.toml` file. (You'll see that for the power sector we have the line `technodata_timeslices = '{path}/technodata/power/TechnodataTimeslices.csv'`, but we don't have a similar line for the residential sector).

There are a couple of ways that we could deal with this - either add the MinimumServiceFactor column in the residential sector file (with everything set to zero) and add the appropriate line in the settings file, or just delete the `TechnodataTimeslices` file in the residential sector. I'd probably go for the second approach to keep the model simple.

You'll find the `default_timeslice` model in `src/muse/data/example`. You'll have modify the model here first, and then propagate these changes to the tutorial models by running the `docs/tutorial-code/generate_models.py` script followed by the `docs/tutorial-code/run_models.py` script  (I can help with this).

**Comment by HarmonicReflux** [comment]
@dalonsoa and @tsmbland,

Please review this pull-request. 

I set the MinimumServiceFactor for the power sector in TechnodataTimeslices.csv to zero and deleted the corresponding unused file in the residential sector. Moreover, I reworked the documentation in the explanatory tutorial notebook and re-run the models using `generate_models.py` and `run_models.py` such that the changes are picked up by the results files.
