### ISSUE TITLE
Create a new repo for the OU course

### ISSUE THREAD

**Issue by tsmbland** [EnergySystemsModellingLab/MUSE_OS#343]
I'm working on updating the [Open University course](https://www.open.edu/openlearncreate/course/view.php?id=11717), and will need to make some changes to the source files. Fortunately Alex Kell (the original author of the course) has made [this nice repo](https://github.com/alexanderkell/muse_teaching_kit) with all the source files and scripts to generate the SCORM package needed for the course.

It probably makes sense to set up a new repo in the EnergySystemsModellingLab org, based on Alex's repo, and make all the changes there. I'm not sure whether it's best to fork Alex's repo and delete all the files that we no longer need, or set up a new repo from scratch and manually copy all the files from Alex's repo that we want to keep. 

The second approach would give us a cleaner repo, as Alex's repo is pretty large (close to 400 MB) and contains a lot of files that we don't need.

The other thing to think about is if we want the new repo to be private or public, as I believe it's not super straightforward to create a private fork of a public repo?

Any thoughts? @dalonsoa @ahawkes

**Comment by ahawkes** [comment]
I favour the cleaner solution (new repo, copy what is needed), but I'm not the expert on what's easiest here, so up to you guys.
________________________________
From: Tom Bland ***@***.***>
Sent: 18 June 2024 11:47
To: EnergySystemsModellingLab/MUSE_OS ***@***.***>
Cc: Hawkes, Adam D ***@***.***>; Mention ***@***.***>
Subject: [EnergySystemsModellingLab/MUSE_OS] Create a new repo for the OU course (Issue #343)


This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



I'm working on updating the Open University course<https://www.open.edu/openlearncreate/course/view.php?id=11717>, and will need to make some changes to the source files. Fortunately Alex Kell (the original author of the course) has made this nice repo<https://github.com/alexanderkell/muse_teaching_kit> with all the source files and scripts to generate the SCORM package needed for the course.

It probably makes sense to set up a new repo in the EnergySystemsModellingLab org, based on Alex's repo, and make all the changes there. I'm not sure whether it's best to fork Alex's repo and delete all the files that we no longer need, or set up a new repo from scratch and manually copy all the files from Alex's repo that we want to keep.

The second approach would give us a cleaner repo, as Alex's repo is pretty large (close to 400 MB) and contains a lot of files that we don't need.

The other thing to think about is if we want the new repo to be private or public, as I believe it's not super straightforward to create a private fork of a public repo?

Any thoughts? @dalonsoa<https://github.com/dalonsoa> @ahawkes<https://github.com/ahawkes>

**Comment by dalonsoa** [comment]
I would fork Alex’s repo and then purge the commit history to leave just the things that are relevant. That way, we keep the connection to the original repo, acknowledging Alex, but remove all the unnecessary stuff.



----------------------------------
Dr Diego Alonso Álvarez (he/him)

Head of Research Software Engineering



[p.s If I send an email outside of your working hours please do not feel the urgency to respond until it is your working hours]



________________________________

**Comment by tsmbland** [comment]
Ok sounds good. @dalonsoa Would you mind creating the fork as I don't have permissions to do this?

**Comment by dalonsoa** [comment]
Done! https://github.com/EnergySystemsModellingLab/muse_teaching_kit

**Comment by tsmbland** [comment]
Thanks @dalonsoa. I can't see an issues page for the new repo. Could you modify the settings to allow this?

**Comment by dalonsoa** [comment]
Solved!
