### ISSUE TITLE
Documentation for installing MUSE (chapter 3.0 to 3.3 in the documentation) should be written clearer

### ISSUE THREAD

**Issue by HarmonicReflux** [EnergySystemsModellingLab/MUSE_OS#357]
The documentation can be improved for clarity. 

For example, 3.2 talks about pipx. Then pyenv is dealt with as a subsection of 3.2, but one can perfectly make use of pyenv without ever touching pipx. For example at the moment we have:
3.2. pipx-based installation
3.2.2.1. Installing pyenv
 
Then, virtual environments are dealt with again in section 3.3, however, it covers conda only. Again, using pyenv along venv, one can perfectly create virutal environments without ever touching conda. Hence, it is confusing to read and sorting chapter 3 better into into clearly separate parts would help clarity. 

Specifically, documentation for conda and pyenv should be considered separately.

**Comment by alexdewar** [comment]
This seems sensible on the face of it.

What does everyone else think? @dalonsoa @tsmbland

**Comment by dalonsoa** [comment]
I agree that is confusing, but a few notes on this:

- `pipx` will create a virtual environment to run the tools it installs based on the python version that was used to install `pipx` to start with, unless you specify another version and that other version is system wide available. Now `muse` works with Python 3.12, so with any modern python version, meaning that before installing `pipx` it was necessary to make sure that the version of `python` it was being used was a valid one. Hence, including the section on `pyenv` there. But I agree it will be better in a dedicated section.
- Either`pyenv`+`venv` or `conda` can be used to create a virtual environment appropriate for MUSE, so while obviously you don't need `conda` when using the first approach, it is a perfectly reasonable approach to setup MUSE. Again, I agree the documentation can be organised better, but I think that both approaches should be described in the virtual environments sections.
