### ISSUE TITLE
python -m pytest throws "4 warnings"

### ISSUE THREAD

**Issue by HarmonicReflux** [EnergySystemsModellingLab/MUSE_OS#360]
The warnings are thrown from the future and appear to be related to jupyter path.

![Screenshot from 2024-06-20 14-56-05](https://github.com/EnergySystemsModellingLab/MUSE_OS/assets/16504600/1627174a-c7ae-4f14-bc32-aa4730360ade)

**Comment by alexdewar** [comment]
There's not a lot we can do about this warning, because it's a jupyter thing. It's not anything we're doing wrong in MUSE -- it's just informing users about an upcoming change.

I came across this warning before. But if you follow the instructions and set that environment variable locally the warning will go away.

You mentioned there were four warnings. Are they all the same?

**Comment by HarmonicReflux** [comment]
Hello @alexdewar,

Yes, the good news is all warning are related to jupyter_client/connect.py and the easy way around it is to invoke, say
`JUPYTER_PLATFORM_DIRS=1 pytest tests/test_docs_notebooks.py`

The above approach avoids cluttering ones .zshrc like so:
``
export JUPYTER_PLATFORM_DIRS=1
source ~/.zshrc
``

Overall, jupyter_core is not yet available in version 6.0, so to me it appears we have to live with the warning unless setting JUPYTER_PLATFORM_DIRS. Invoking `pip show jupyter_core` tells me I am running on version 5.7.2, and version 6.0 that should make the warning to disappear "outside the box" is not yet available, which one can confirm via
`pip install jupyter_core==6.0.0`
So for the time being there is nothing we can do. I could ass a sentence in the documentation, but given this warning will be temporary only and is not related to MUSE_OS directly, should we just let it go?

**Comment by alexdewar** [comment]
Yep, I think we should let it go.

Thanks for looking into this!

**Comment by HarmonicReflux** [comment]
I'd like to document another observation that extends what I mentioned in today's stand up session.

When I opened issue #360, all notebooks run without failures. However, working on this issue yesterday, notebook 2: further-extending-muse.ipynb and notebook 3: extending-muse.ipynb failed the tests. 

Notebook 2 and 3 failed with an AttributeError when attempting to run the following code:
```
mca = MCA.factory(os.path.join(model_path, "settings.toml"))
mca.run();

The error traceback shows:
AttributeError: module 'xarray' has no attribute 'Coordinates'
```
There was also an issue with pandas.Multiindex.

I updated my libraries like so (I hoped updating the jupyter suite would eliminate the warnings, but didn't )
pip install --upgrade xarray pandas jupyter jupyter_client nbclient nbconvert

This then left me with xarray version 2022.6.0 and pandas version 2.2.2
`python -m pytest -v tests/test_docs_notebooks.py` then permits the notebook tests pass without failures.

pip list | grep -E 'jupyter|jupyter_client|nbclient|nbconvert' reveals:
jupyter                       1.0.0
jupyter_client                8.6.2
jupyter-console               6.6.3
jupyter_core                  5.7.2
jupyter-events                0.10.0
jupyter-lsp                   2.2.5
jupyter_server                2.14.1
jupyter_server_terminals      0.5.3
jupyterlab                    4.2.1
jupyterlab_pygments           0.3.0
jupyterlab_server             2.27.2
jupyterlab_widgets            3.0.11
nbclient                      0.10.0
nbconvert                     7.16.4


Despite all notebook test now passing, the above upgrades trigger:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
muse-os 1.1.0 requires pandas<=1.3, but you have pandas 2.2.2 which is incompatible.
muse-os 1.1.0 requires xarray==2022.3.0, but you have xarray 2024.6.0 which is incompatible.

**Comment by alexdewar** [comment]
When do you see this error message? It seems to me like those are the *old* version requirements for `pandas` and `xarray`, so maybe you've accidentally installed the `muse-os` package somewhere? We don't have those constraints in place anymore, so you should just get the latest versions.

**Comment by HarmonicReflux** [comment]
The two test-failing notebooks (which after upgrading xarray and pandas pass the tests again), unexpectedly failed running the tests this week. I set up muse in the beginning of May following the "developer's" section of the documentation that I then helped improve. 

Can I be bold and invoke
python -m pip install -e .[dev,doc]
(which should be equivalent to `pip install --upgrade muse` for the stand-alone version)

If that is too bold indeed, maybe its a good idea setting it up from scratch.

**Comment by tsmbland** [comment]
`pip install -e .[dev,doc]` won't necessarily update the dependencies, because we're still not specifying minimum versions for packages in the `pyproject.toml` file (I think this is something we should definitely do though)

I would usually do `pip install --upgrade --upgrade-strategy eager -e .[dev,doc]`

However, I think the best strategy in this case would be to set up the environment from scratch
