### ISSUE TITLE
Add script for regenerating data in `tests/example_outputs`

### ISSUE THREAD

**Issue by alexdewar** [EnergySystemsModellingLab/MUSE_OS#361]
This is partly a small QoL improvement, but having a way of regenerating this data programatically is also a prerequisite for making it possible to run regression tests without having to store the results in the git repo (see #351).

Are we happy that this makes sense regardless of what solution we come up with for #351? @dalonsoa @tsmbland

**Comment by dalonsoa** [comment]
I'm not sure, to be honest. The whole point of regression tests is that new data created with the latest version is the same than the one created with a previous one, and if it changes, it is for a good, understood reason. If we are creating data programmatically, it does not make sense to use that data in regression tests, and it will be using the latest (potentially wrong) version of the code and not the older (in principle correct) version.

Am I missing anything?

**Comment by tsmbland** [comment]
I think the point is that you'd only run this if you've intentionally made a change to the model that you know will change the results. Just saves you from having to run all of the example models individually to update the results files. 

Or, it could be part of a more complex CI workflow like the one that Alex suggested in #351, but in this case it will only be run with old versions of the code which are known to be correct
