### ISSUE TITLE
Minimum service factor is applied incorrectly

### ISSUE THREAD

**Issue by alexdewar** [EnergySystemsModellingLab/MUSE_OS#375]
Currently, we seem to be multiplying utilisation factor by minimum service factor, which is not the correct calculation. (I guess this means that the minimum is treated as being a proportion of utilisation factor?)

See: https://github.com/EnergySystemsModellingLab/MUSE_OS/blob/a2a1b4f3d8bf4166ee57056b569584234a454883/src/muse/constraints.py#L533

@dalonsoa I may have misremembered, but did you say that there were other places in the code where we're using this value incorrectly?

**Comment by dalonsoa** [comment]
It is being implemented somewhere else in #368. But it is not clear if that PR is actually needed - based on the discussions taking place in #335 - and even if it is, I will obviously fix that PR directly.

**Comment by dalonsoa** [comment]
In summary, I think that's the only place where it is used the wrong way.

**Comment by tsmbland** [comment]
See also #382

**Comment by tsmbland** [comment]
Closed by #388
