### ISSUE TITLE
`find_equilibrium` function always terminates on the second iteration [BUG]

### ISSUE THREAD

**Issue by tsmbland** [EnergySystemsModellingLab/MUSE_OS#406]
I've been looking at the `find_equilibrium` function in `mca.py` to try and understand what the  `maximum_iterations` parameter is doing, as discussed in #372.

This function contains a loop which iteratively solves each sector (via the `single_year_iteration` function) and adjusts the price of each commodity accordingly. It then checks whether an equilibrium has been reached, and if not, moves to the next iteration to solve each sector again with the new commodity prices. The loop will finally terminate once an equilibrium is reached (i.e. when the change in supply and demand from iteration-to-iteration falls below a threshold). The `maximum_iterations` parameter defines the maximum number of times that this loop is allowed to run without converging.

Well I think that's the intention, but the function is one big mess.

To start with, there's a whole load of price manipulations within the function (e.g. [here](https://github.com/EnergySystemsModellingLab/MUSE_OS/blob/2e8e1b5d8d93317b4c6be361deaa43691606eaf0/src/muse/mca.py#L586)) which don't appear to be doing anything and just get overwritten by the `market["prices"] = drop_timeslice(market.updated_prices)` line at the top of the loop. I think possibly the intention here was to buffer the iteration-on-iteration price changes, but I'm not sure if this is really necessary (and in any case, it's not being used).

But I think there's a much bigger problem - it seems that loop is guaranteed to terminate on the second iteration (at least when `equilibrium_variable` is "demand" - I think when `equilibrium_variable` is "prices" it will always terminate on the third iteration (maybe)).

To make this clearer, I've written a tidier version of the function ([here](https://github.com/EnergySystemsModellingLab/MUSE_OS/blob/c963227bcb9abbe829979cfbb0bea4b2b25adb01/src/muse/mca.py#L507)) which removes all of the unused computations, but should have the same behaviour (the tests are passing, at least). Looking at this, I think the problem is to do with the `prior_market, market = market, prior_market` line at the top of the loop. This sets `prior_market` to the `market` solved from the previous iteration (which is what we want), but it also reverts `market` back to the previous previous value (confused?), which then gets solved. The net result is that in the second iteration you end up comparing two markets that have been solved once with the same prices, so the convergence criteria always passes and the loop always terminates.

Just to convince yourselves further, try changing `maximum_iterations` for any model from 100 to 2, and you should get identical results.

I think a simple solution would be to change `prior_market, market = market, prior_market` to `prior_market = market.copy(deep=True)`. There may be more efficient solutions, but this seems to work and not always terminate on the second iteration.

I also think the convergence checks need another look, but let's get the loop working first.

**Comment by ahawkes** [comment]
Right! Wow. This is indeed dire. Thanks for the initial fix.

In the background there is an issue of how one actually gets things to converge - it can be hard (sometimes impossible) given that users can essentially make sectors behave any way they want (e.g. highly non-linear, massive step changes, etc).

But for now let's see if we can get this working for relatively smooth models. Understanding what exactly is meant by tolerance would be useful.
