### ISSUE TITLE
Remove use of `bump2version`

### ISSUE THREAD

**Issue by alexdewar** [EnergySystemsModellingLab/MUSE_OS#435]
Currently we're using `bump2version` whenever we want to bump the version number in order to make a new release. This process is also currently not documented #436.

I've just had a fairly frustrating experience with @tsmbland trying to make it create a new `rc` release, without success. Thinking about it, I'm not sure we need `bump2version` at all. Nowadays you can just specify the version number in `pyproject.toml`; if you need to access the version number from the source code you can get it with `importlib` anyway.

**Comment by tsmbland** [comment]
@AdrianDAlessandro Files to look at:
- `.bumpversion.cfg`
- `CITATION.cff`
- `docs/conf.py`
- `src/muse/__init__.py`
