### ISSUE TITLE
Remove `develop` branch

### ISSUE THREAD

**Issue by alexdewar** [EnergySystemsModellingLab/MUSE_OS#441]
In other projects we've increasingly been just using a `main` branch without a separate `develop` branch. Personally, I'm not sure having a `develop` branch offers much. While it does mean that you can have your `main` branch just be composed of the versions of the code that you want your users to use, you can achieve this just as well by making releases. The downside of having two separate main branches is that you have to have two sets of branch protection rules etc. and they can end up out of sync, with strange failures happening when you merge from `develop` to `main`.

I don't think we need to do this immediately, but it might make our lives slightly easier in the long run.

**Comment by tsmbland** [comment]
Done
