### ISSUE TITLE
Questions regarding MaxGrowthCapacity 

### ISSUE THREAD

**Issue by sharwaridixit** [EnergySystemsModellingLab/MUSE_OS#455]
Section 9.3.3 describes the constraints defined in the Technodata input file, however I am a little unsure of how the MaxCapacityGrowth is used in a MUSE run. This is the description:
<img width="811" alt="Screenshot 2024-08-15 at 11 16 36" src="https://github.com/user-attachments/assets/60ae427a-52b5-4fe3-af45-a1d30029371e">

The example given for how the MaxCapacityGrowth works shows a linear growth being applied to the capacity in the investment year, depending on the time interval. I was wondering whether this initial capacity is the 'seed value', i.e. is the seed value for this growth the initial existing capacity set in the existing capacity input file? What happens if this seed value is 0? My understanding of how this constraint works is not completely clear. 
Also, having discussed with Adam, would it make more sense to make the growth work as a compound growth as opposed to linear?

Thank you.

**Comment by tsmbland** [comment]
Hi @sharwaridixit and @ahawkes 

Sorry for the delay in looking at this. 

If existing capacity is zero, then the MaxCapacityGrowth constraint is not applied. So in the first year that an asset is installed, only MaxCapacityAddition and TotalCapacityLimit apply. After that, all three constraints are applied. This is the same for both the scipy and adhoc solvers.

I agree that this is not at all clear from the documentation. I also agree that compound growth would be more appropriate, and this would be very easy to implement

**Comment by Jin-Jun-Mei** [comment]
I have a different question about these parameters:  MaxCapacityAddition/Limit. 
The unit used here is PJ, which is a unit of Energy, shouldn't the unit be unit of Power?? Such as MW/year ???

**Comment by tsmbland** [comment]
Hi @Jin-Jun-Mei,
To clarify, capacity here refers to potential output over the course of a year when operating at full capacity. So, if you have capacity data in W, you need to multiply it by 3.154e+7 (the number of seconds in a year) to get energy in J. Or converting MW to PJ, multiply by 31.54.
