### ISSUE TITLE
Utilization factor column mandatory in `Technodata.csv` even when specified in `TechnodataTimeslice.csv`

### ISSUE THREAD

**Issue by tsmbland** [EnergySystemsModellingLab/MUSE_OS#513]
If UF is specified in `TechnodataTimeslice.csv`, any UF specified in the `Technodata.csv` file will be overwritten. Nevertheless, MUSE will complain if this column is missing in the `Technodata.csv` file

**Comment by Jin-Jun-Mei** [comment]
If one has any 0 value in UF in the _Technodata.csv_, MUSE will also complain this: _"ValueError: A technology can not have a utilization factor of 0 for every timeslice."._   Even though, the UF in the _TechnodataTimeslice.csv_ is not all 0 for a technology.

**Comment by tsmbland** [comment]
@dalonsoa The problem is to do with the `check_utilization_and_minimum_service_factors` function. It gets called when reading both `Technodata.csv` (`read_technologies`) and `TechnodataTimeslices` (`read_technodata_timeslices`), which means that the UF column must be there in both files. A solution might be to move this check over to the `read_technologies` function and perform these checks on the final technologies object.
