### ISSUE TITLE
Delete the `ObjSort` parameter from `TechnodataTimeslices.csv`

### ISSUE THREAD

**Issue by tsmbland** [EnergySystemsModellingLab/MUSE_OS#514]
Not sure what this parameter is intended for, but it's not doing anything, nor is it mentioned in the documentation, so let's remove it from the `default_timeslice` model

**Comment by Jin-Jun-Mei** [comment]
Is there an _ObjSort_ parameter in the _TechnodataTimeslices.csv_?? I don't think I have it in my _TechnodataTimeslices.csv_.

**Comment by tsmbland** [comment]
It works fine without this column, so if you don't have it in your file you can ignore this.

But for some reason the `default_timeslice` model that's included with MUSE has this column and it's not doing anything. I guess it's a legacy thing and just hasn't been deleted yet.
