### ISSUE TITLE
Inconsistent numbers in the documentation 

### ISSUE THREAD

**Issue by Jin-Jun-Mei** [EnergySystemsModellingLab/MUSE_OS#536]
## Describe the bug
In the documentation (Section 8.2.1, "Addition of Cooking Demand"), it says, "For simplicity, we will **copy over** the values from the heat column." However, if you looked at the numbers in the table, they are not the same as in the heat column as described.

I know this is a very minor detailed thing, but just want to point out, in case someone runs the example model, and get different results.

**Comment by tsmbland** [comment]
Fixed by https://github.com/EnergySystemsModellingLab/MUSE_OS/commit/94f5fb9f6bc58e54c85c224dacb8a3ac7ce558a1

Thanks for spotting!
